name: PlatformIO CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache pip
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Cache PlatformIO
      uses: actions/cache@v2
      with:
        path: ~/.platformio
        key: ${{ runner.os }}-${{ hashFiles('**/lockfiles') }}
    - name: Set up Python
      uses: actions/setup-python@v2
    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Build inca_1
      run: pio run -e inca_1
    - name: Build inca_2
      run: pio run -e inca_2
    - name: Build inca_3
      run: pio run -e inca_3
    - name: Build LOGO
      run: pio run -e LOGO
    - name: Build carre_1
      run: pio run -e carre_1
    - name: Build carre_2
      run: pio run -e carre_2
    - name: Deploy
      env:
        SUPER_SECRET: ${{ secrets.TOKEN }} 
      run: |
        mv .pio/build/inca_1/firmware.bin      DMX2LEDs_inca_1.bin
        mv .pio/build/inca_2/firmware.bin      DMX2LEDs_inca_2.bin
        mv .pio/build/inca_3/firmware.bin      DMX2LEDs_inca_3.bin
        mv .pio/build/LOGO/firmware.bin        DMX2LEDs_LOGO.bin
        mv .pio/build/carre_1/firmware.bin     DMX2LEDs_carre_1.bin
        mv .pio/build/carre_2/firmware.bin     DMX2LEDs_carre_2.bin

        curl -sSF file=@DMX2LEDs_inca_1.bin  'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_inca_2.bin  'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_inca_3.bin  'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_LOGO.bin    'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_carre_1.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET
        curl -sSF file=@DMX2LEDs_carre_2.bin 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


        echo `TZ="Europe/Paris" date '+%F %T'`" git:"`git rev-parse --short HEAD` > DMX2LEDs.info
        curl -sSF file=@DMX2LEDs.info 'http://antoine.doussaud.org:25478/upload?token='$SUPER_SECRET


